In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
voc_size = 10000

In [8]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
import numpy as np
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5290 5660 6286 8547]
 [   0    0    0    0 5290 5660 6286 5138]
 [   0    0    0    0 5290 3640 6286 9109]
 [   0    0    0 1498   74 4765 1077 5441]
 [   0    0    0 1498   74 4765 1077 7299]
 [   0    0    0 3924 5290 7940 6286 4637]
 [   0    0    0    0 9382 3424  587 1077]]


In [13]:
## feature representation
dim=10

In [16]:
#model
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

c:\Users\varde\anaconda3\envs\genai\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 460ms/step


array([[[ 0.01676852,  0.04279182,  0.01378398,  0.02683637,
         -0.04250034,  0.02155733,  0.01392981, -0.03347931,
         -0.03265554,  0.03400166],
        [ 0.01676852,  0.04279182,  0.01378398,  0.02683637,
         -0.04250034,  0.02155733,  0.01392981, -0.03347931,
         -0.03265554,  0.03400166],
        [ 0.01676852,  0.04279182,  0.01378398,  0.02683637,
         -0.04250034,  0.02155733,  0.01392981, -0.03347931,
         -0.03265554,  0.03400166],
        [ 0.01676852,  0.04279182,  0.01378398,  0.02683637,
         -0.04250034,  0.02155733,  0.01392981, -0.03347931,
         -0.03265554,  0.03400166],
        [-0.00350878, -0.03243983, -0.04575876,  0.04367908,
          0.03767443,  0.04254505,  0.01127752,  0.04845402,
          0.00050931, -0.00584453],
        [-0.01657722,  0.00368058, -0.02536076, -0.02317972,
          0.01609328, -0.02965629, -0.0137113 ,  0.03015264,
         -0.02629749,  0.04369999],
        [ 0.00575401,  0.01093302, -0.00505709,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 5290, 5660, 6286, 8547], dtype=int32)